server:
  port: 8111

spring:
  # Datasource
  datasource:
    username: postgres
    password: secret
    url: jdbc:postgresql://localhost:5432/yourcast
  jpa:
    show-sql: true

jwt:
  secret: hARKGnYYRMFNp9vGWiP5F9vlnAQ4OA9b
  expire: 60000
  issuer: your-cast.com