service:
  name: ${spring.application.name}
  version: 0.0.1

spring:
  application:
    name: yourcast-api
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER}
  # Database
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      pool-name: yourcast-api-db-cp
      connection-test-query: SELECT 1
      idle-timeout: 100000
      connection-timeout: 10000
      max-lifetime: 300000
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 30

logging:
  level:
    root: INFO
  pattern:
    dateformat: "dd.MM.yyyy HH:mm:ss.SSS"

springdoc:
  version: 1.0.0

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRE}
      issuer: ${JWT_ISSUER}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRE}

DATASOURCE_USERNAME:
DATASOURCE_PASSWORD:
DATASOURCE_URL:

JWT_SECRET:
JWT_EXPIRE:
JWT_REFRESH_EXPIRE:
JWT_ISSUER: