name: Test

on:
  push:
    branches:
      - 'main'
      - 'release-**'
  pull_request:
    branches:
      - 'main'
      - 'release-**'

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: yourcast
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

  steps:
    name: Tests NestJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test:e2e
        env:
          DB_HOST: postgres
          DB_PORT: 5432
          DB_NAME: yourcast
          DB_USERNAME: postgres
          DB_PASSWORD: secret
