name: GitHub Action YourCast CI/CD

on:
  push:
    branches:
      - 'main'
      - 'release/*'
  pull_request:
    branches:
      - 'main'
      - 'release/*'

jobs:
  ci:
    name: CI

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

  deploy:
    name: DEPLOY

    needs: [ci]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag kuchura/your-cast-api:1.0.0-$(echo $GITHUB_SHA | cut -c1-7)

      - name: Docker Push
        run: docker push kuchura/your-cast-api:1.0.0-$(echo $GITHUB_SHA | cut -c1-7)